### ISSUE TITLE
Default group doesn't apply permissions correctly

### ISSUE THREAD

**Issue by CaptainSisko** [Thutmose/ThutPerms#17] opened 2018-04-29 03:53 UTC
**I am currently running...**
- Mod version: thutpermissions-1.12.2-2.0.3.jar
- Forge version:  forge-1.12.2-14.23.3.2674-universal.jar
- Java version: 1.8.0_162
- Operating System: Ubuntu 16.04.4 LTS

**What is the expected result?**
Members of the `default` group that is created on the first server launch should be able to use all of the commands associated with the permissions set on that group. (e.g /spawn)

**What is the current result?**
The `default` group does not apply any of the permissions that it has configured by default or any that are added manually.

If a player in the `default` group attempts to use a command that has the correct permissions configured they receive the following message

[You do not have permissions to use /spawn](https://puu.sh/Ac3Es/169981cc59.png)

If `/editPerms default all true` is set, players in the `default` group will have access to all commands (which is the expected function).

Removing a player from the `default` group then re-adding the player has no effect.

If a new group is created and the permissions are copied with `/copyGroup default newGroup` the `newGroup` experiences the same issue as the `default` group.

It is possible to get the `default` group to work by following these steps howerver this only works until you reboot the server so its practically useless.
- Stop your server
- Delete the `permissions` folder located inside the `world` folder
- Start your server and dont let anyone join
- Rename the `default` group with `/renameGroup default defaultOld` 
- Create a new group with `/addGroup newGroup`
- Manually assign ALL permissions with `/editperms newGroup thut.essentials.commands.misc.Spawn true` etc.
- Rename `newGroup` to `default` with `/renameGroup newGroup default`
- Join the server

Unfortunately this "workaround" requires you to set all the permissions that you require in one go as making any changes to the permissions after this will not work. Making changes then leaving/rejoining or even just rebooting the server will result in a crash. The only way to stop this crash that i have found so far is to delete the `world\permissions` folder and start again.

Crash log - https://gist.github.com/CaptainSisko/8f4c11d9909afd2883b841e5a3d5dbd4

**Comment by Thutmose** [comment] 2018-04-29 17:16
this is a duplicate of #15, I will get it fixed whenever i have time, which, hopefully will be sometime after thursday, until then, I am very busy with some other things, so don't have time to look into minecraft stuff.

**Comment by CaptainSisko** [comment] 2018-04-30 02:34
No Dramas, thanks for the quick response.

I mainly wanted to make sure that this issue was logged correctly and with enough information for you to completely understand the problem when you come to fix it.

**Comment by Thutmose** [comment] 2018-04-30 19:04
ya, the crash log should help narrow things down, when I took a brief look at it when #15 was posted, I didn't see anything glaringly wrong, so having a variety of crash reports to look at should help.

**Comment by Thutmose** [comment] 2018-05-06 00:05
Try it with the jar I uploaded here: https://github.com/Thutmose/ThutPerms/issues/18 let me know if it works, or re-send crash log if it doesnt

**Comment by Thutmose** [comment] 2018-05-07 02:15
this should be fixed as of the 2.0.4 which has been uploaded to curseforge

**Closed as completed by Thutmose** 2018-05-07 02:15 UTC
Labels: duplicate
